name: Update README (Latest Commits)

on:
  push:
    paths:
      - "README.md"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Get latest commits
        run: |
          echo "## ðŸ—‚ï¸ Ãšltimos repos actualizados / Latest Updated Repos" > REPOS.md
          git log -5 --pretty=format:"- %h - %s (%ci)" >> REPOS.md

      - name: Update README
        run: |
          sed -i '/<!--START_SECTION:repos-->/r REPOS.md' README.md
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if git diff --quiet; then
            echo "No changes."
          else
            git add README.md
            git commit -m "chore(readme): refresh latest commits"
            git push
          fi
